premierlangage-master/server/serverpl/gitload/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^browse/$', views.browse),
    url(r'^view_file/$', views.view_file),
    url(r'^loaded_pltp/$', views.loaded_pltp),
    url(r'^loaded_pl/$', views.loaded_pl),
    url(r'^activity/$', views.activity),
    url(r'^edit_file/$', views.edit_file),
]

premierlangage-master/server/serverpl/playexo/urls.py
 # coding: utf-8
 
from django.conf.urls import url

from . import views
from gitload.views import index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^not_authenticated/.*$', views.not_authenticated),
    url(r'^activity/lti/(\w+)/(\w+)/$', views.lti_receiver),
    url(r'^activity/test/(\w+)/(\w+)/$', views.test_receiver),
    url(r'^activity/$', views.activity_view),
    url(r'^try/$', views.try_pl),
]

premierlangage-master/server/serverpl/classmanagement/models.py
from django.db import models
from django.contrib.auth.models import User

from playexo.models import Activity

class Role(models.Model):
    """ Default role are created at migration. See 'playexo/migrations/xxxx_add_role_data.py'
        If you add a new default role, do not forget to add it to the migration file. """
        
    ADMINISTRATOR = 'AD'
    INSTRUCTOR = 'IN'
    CONTENT_DEVELOPER = 'CD'
    LEARNER = 'LE'
    OBSERVER = 'OB'
    ROLES = (
        (ADMINISTRATOR, 'Administrator'),
        (INSTRUCTOR, 'Teacher'),
        (CONTENT_DEVELOPER, 'Conceptor'),
        (LEARNER, 'Student'),
        (OBSERVER, 'Observeur'),
    )
    
    role = models.CharField(primary_key = True, max_length=2, choices=ROLES, null = False, default=LEARNER)
    
    def __str__(self):
        return self.role



class PLUser(models.Model):
    """ Extends User to add a Role and Color Blindness"""
    
    PROTANOPIA = 'PR'
    DEUTERANOPIA = 'DE'
    TRITANOPIA = 'TR'
    NONE = 'NO'
    COLOR_BLINDNESS = (
        (PROTANOPIA, 'Protanope'),
        (DEUTERANOPIA, 'Deuteranope'),
        (TRITANOPIA, 'Tritanope'),
        (NONE, 'Aucun'),
    )
    
    user = models.OneToOneField(User, primary_key = True, on_delete=models.CASCADE, null = False)
    role = models.ManyToManyField(Role, blank=True)
    activity = models.ManyToManyField(Activity, blank=True)
    color_blindness = models.CharField(max_length=2, choices=COLOR_BLINDNESS, null=False, default=NONE)
    
    def is_admin(self):
        return (Role.objects.get(role=Role.ADMINISTRATOR) in self.role.all() or self.user.is_staff or self.user.is_superuser)
    
    def can_load(self):
        return (self.have_role(Role.INSTRUCTOR) or self.have_role(Role.CONTENT_DEVELOPER) or self.is_admin())
    
    def have_role(self, role):
        return (Role.objects.get(role=role) in self.role.all())
    
    def set_role(self, role):
        if not self.have_role(role):
            self.role.add(role)
    
    def unset_role(self, role):
        if self.have_role(role):
            self.role.remove(role)


class Course(models.Model):
    id = models.CharField(max_length=30, primary_key=True, null = False)
    name = models.CharField(max_length=200, null = False)
    label = models.CharField(max_length=20, null = False)
    user = models.ManyToManyField(User)
    activity = models.ManyToManyField(Activity)
            
    def __str__(self):
        return str(self.id)+": ["+self.label+"] "+self.name

premierlangage-master/server/serverpl/playexo/models.py
# coding: utf-8

from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from gitload.models import PLTP, PL



class Activity(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=200, null=False)
    pltp = models.ForeignKey(PLTP, null=False, on_delete=models.CASCADE)
    open = models.BooleanField(null = False, default = True)
    
    def __str__(self):
        return str(self.id)+" "+self.name


class ActivityTest(models.Model):
    name = models.CharField(max_length=200, null=False)
    pltp = models.ForeignKey(PLTP, null=False,  on_delete=models.CASCADE)
    date = models.DateTimeField(null=False, default=timezone.now)
    
    
    @staticmethod
    def delete_outdated():
        now = datetime.utcnow()
        activities = ActivityTest.objects.get.all().sort_by("date")
        for activity in activities:
            if (datetime.utcnow() - activity.date) > timedelta(days=1):
                activity.delete()
            else:
                break
                
        
    def __str__(self):
        return self.name


class Answer(models.Model):
    STARTED = 'ST'
    FAILED = 'FA'
    SUCCEEDED = 'SU'
    NOT_STARTED = 'NS'
    STATE = (
        (STARTED, 'Commencé'),
        (FAILED, 'Echoué'),
        (SUCCEEDED, 'Réussi'),
    )
    
    value = models.TextField(max_length = 50000, null = False)
    user = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    pl = models.ForeignKey(PL, null=False, on_delete=models.CASCADE)
    seed = models.CharField(max_length=50, null=True)
    date = models.DateTimeField(null = False, default=timezone.now)
    state = models.CharField(max_length=2, choices=STATE, null=False, default=STARTED)
    
    
    @staticmethod
    def pl_state(pl, user):
        """
            Return the state of the answer associated to this pl and user following these rules in this order:
                - If no answer exists: Answer.NOT_STARTED
                - If at least one good answer exists: Answer.SUCCEEDED
                - If at least one bad answer exists: Answer.FAILED
                - Otherwise: Answer.STARTED
            TL,DR: Success prevail over fail which prevail over save/reload.
        """
        
        answers = Answer.objects.filter(user=user, pl=pl)
        if not answers:
            return Answer.NOT_STARTED
        
        failed = False
        for item in answers:
            if item.state == Answer.SUCCEEDED:
                return Answer.SUCCEEDED
            if item.state == Answer.FAILED and not failed:
                failed = True
        
        if failed:
            return Answer.FAILED
        return Answer.STARTED
    
    
    @staticmethod
    def pltp_state(pltp, user):
        """ Return a list of tuples (pl_sha1, state) where state follow pl_state() rules. """
        
        lst = list()
        for pl in pltp.pl.all():
            lst.append((pl.sha1, Answer.pl_state(pl, user)))
            
        return lst
    
    
    @staticmethod
    def pltp_summary(pltp, user):
        """
            Give information about the PLTP's completion of this user as a dict of 3 tuples:
            {
                'succeeded': (% succeeded, nbr succeeded),
                'failed': (% failed, nbr failed),
                'started: (% started, nbr started),
                'not_started': (% not started, nbr not started),
            }
        """
    
        succeeded = 0
        failed = 0
        started = 0
        not_started = 0
        for pl, state in Answer.pltp_state(pltp, user):
            if state == Answer.SUCCEEDED:
                succeeded += 1
            elif state == Answer.FAILED:
                failed += 1 
            elif state == Answer.STARTED:
                started += 1
            else:
                not_started += 1
                        
        nb_pl = succeeded + failed + started + not_started
        if not nb_pl:
            nb_pl = 1
        state = {
            'succeeded':    (str(succeeded*100/nb_pl), str(succeeded)),
            'failed':       (str(failed*100/nb_pl), str(failed)),
            'started':      (str(started*100/nb_pl), str(started)),
            'not_started':  (str(not_started*100/nb_pl), str(not_started)),
        }
        
        return state
    
    
    @staticmethod
    def course_state(course):
        """ 
            Return every pltp state of every user of this course as a list of dicts:
            {
                'user_id': id,
                'pltp_sha1' sha1,
                'pl': list(pl_sha1, state)
            }
            where 'state' follow pl_state() rules.
        """
        
        lst = list()
        for user in course.user:
            dct = dict()
            dct['user_id'] = user.id
            for activity in course:
                dct['pltp_sha1'] = activity.pltp.sha1
                dct['pl'] = Answer.pltp_state(activity.pltp, user)
            lst.append(dct)
        
        return lst
    
    
    @staticmethod
    def user_course_summary(course, user):
        """
            Give information about the completion of every PL of this user in course as a dict of 3 tuples:
            {
                'succeeded': (% succeeded, nbr succeeded),
                'failed': (% failed, nbr failed),
                'started: (% started, nbr started),
                'not_started': (% not started, nbr not started),
            }
            where finished pl are either failed or succeeded pl.
        """
    
        succeeded = 0
        failed = 0
        started = 0
        not_started = 0
        for activity in course.activity.all():
            for pl, state in Answer.pltp_state(activity.pltp, user):
                if state == Answer.SUCCEEDED:
                    succeeded += 1
                elif state == Answer.FAILED:
                    failed += 1
                elif state == Answer.STARTED:
                    started += 1
                else:
                    not_started += 1
                        
        nb_pl = succeeded + failed + started + not_started
        if not nb_pl:
            nb_pl = 1
        state = {
            'succeeded':    (str(succeeded*100/nb_pl), str(succeeded)),
            'failed':       (str(failed*100/nb_pl), str(failed)),
            'started':      (str(started*100/nb_pl), str(started)),
            'not_started':  (str(not_started*100/nb_pl), str(not_started)),
        }
        
        return state

premierlangage-master/server/serverpl/playexo/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Python 3.5.4
#
#  Author: Coumes Quentin     Mail: qcoumes@etud.u-pem.fr
#  Created: 2017-07-05
#  Last Modified: 2017-11-16

import json, traceback, logging, timeout_decorator, time

from sympy import evaluate

from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse
from django.contrib import messages

from gitload.models import PLTP, PL

from playexo.exercise import Exercise, ExerciseTest
from playexo.builder import PythonBuilder, PythonBuilderTest
from playexo.models import Activity, ActivityTest, Answer
from playexo.strategy import strategy as default_strategy

from classmanagement.models import Course


logger = logging.getLogger(__name__)


@csrf_exempt
@login_required
def activity_view(request):
    activity_id = request.session.get("current_activity", None)
    if activity_id == None:
        return HttpResponse("No activity found in the session", status=409)
    
    if request.session.get("testing", False):
        activity = get_object_or_404(ActivityTest, id=activity_id)
    else:
        activity = get_object_or_404(Activity, id=activity_id)
    
    dic = json.loads(activity.pltp.json)
    if "strategy" in dic:
        request.session["test_strategy"] = True
        try:
            exec(dic["strategy"], globals())
            strategy = globals()['strategy']
        except Exception as e:
            return render(request, 'playexo/strategy_failed.html', {'exc_type': str(type(e)), 'exc_msg': str(e), 'exc_trace': traceback.format_exc().replace('\n', '<br>')})
    else:
        strategy = default_strategy
    
    try:
        return strategy(request, activity)
    except Exception as e:
        return render(request, 'playexo/strategy_failed.html', {'exc_type': str(type(e)), 'exc_msg': str(e), 'exc_trace': traceback.format_exc().replace('\n', '<br>')})
    


@login_required
@csrf_exempt
def lti_receiver(request, activity_name, pltp_sha1):
    activity_id = request.session.pop("activity", None)
    course_id = request.session.pop("course_id", None)
    if not activity_id or not course_id:
        raise Http404("Impossible d'accéder à la page, la requête LTI doit contenir une ID d'activité ainsi que d'une ID de classe.")
    
    try:
        activity = Activity.objects.get(id=activity_id)
    except:
        try:
            pltp = PLTP.objects.get(sha1=pltp_sha1)
        except:
            raise Http404("Impossible de charger le TP associé à cette activité, celle-ci n'existe peut être plus sur la plateforme, merci de contacter votre professeur")
        activity = Activity(name=activity_name, pltp=pltp, id=activity_id)
        activity.save()
        logger.info("New activity created: '"+activity_name+" ("+str(activity_id)+")' and added to course of id "+str(course_id))
    Course.objects.get(id=course_id).activity.add(activity)
    
    request.session['current_activity'] = activity_id
    request.session['current_pl'] = None
    request.session['testing'] = False
    request.session['strategy_session'] = dict()
    return HttpResponseRedirect(reverse(activity_view))



@login_required
@csrf_exempt
def test_receiver(request, activity_name, pltp_sha1):
    pltp = get_object_or_404(PLTP, sha1=pltp_sha1);
    activity = ActivityTest(pltp=pltp, name=activity_name)
    activity.save();
    
    request.session['current_activity'] = activity.id
    request.session['current_pl'] = None
    request.session['testing'] = True
    request.session['strategy_session'] = dict()
    return HttpResponseRedirect(reverse(activity_view))



@login_required
@csrf_exempt
def try_pl(request, pl=None, warning=None):
    with evaluate(False):
        exercise = request.session.get('exercise', None)
    success = None
    feedback = None
    
    if pl:
        messages.success(request, "Le PL <b>"+pl.name+"</b> a bien été chargé.")
        messages.warning(request, warning)
        messages.error(request, "Attention, ceci est une session de test, les réponses ne seront pas enregistrer après la fermeture de la fenêtre (Pensez à copier/coller).")
    
    if not exercise:
        pl_dic = pl.json
        exercise = PythonBuilderTest(pl_dic).get_exercise()
    else:
        exercise = ExerciseTest(exercise)
    
    if request.method == 'GET' or request.method == 'POST':
        status = None
        try:
            status = json.loads(request.body.decode())
        except:
            pass
        if status and status['requested_action'] == 'submit' :
            success, feedback = exercise.evaluate(status['inputs'])
            if (success):
                feedback_type = "success"
            else:
                feedback_type = "failed"
            return HttpResponse(json.dumps({'feedback_type': feedback_type, 'feedback': feedback}), content_type='application/json')
            
    request.session['exercise'] = exercise.dic
    return HttpResponse(exercise.render(request, feedback, success))



def not_authenticated(request):
    logout(request)
    return render(request, 'playexo/not_authenticated.html', {})

premierlangage-master/server/serverpl/playexo/templates/playexo/alert.html
{% comment "Info" %}
    A inclure dans la plupart des template après la top barre.
    Permet d'afficher des message d'alerte (petit pop up fermable juste en dessous de la top barre) afin
    d'avertir/donner des informations à l'utilisateurs.
    Pour créer une alerte, simplement faire un:
        - from django.contrib import messages puis
            - messages.success(request, msg) ou
            - messages.info(request, msg) ou
            - messages.warning(request, msg) ou
            - messages.error(request, msg)
    dans la vue correspondante.
{% endcomment %}

<div class="row">
    <div class=col-md-2></div>
    <div class=col-md-8>
        {% for message in messages %}
            <div id="message" class="alert alert-{{ message.tags }} alert-dismissable" style="margin-top: -20px">
                {% if message.tags == "danger" %}
                    <span class="glyphicon glyphicon-fire"></span>
                {% elif message.tags == "success" %}
                    <span class="glyphicon glyphicon-ok"></span>
                {% elif message.tags == "info" %}
                    <span class="glyphicon glyphicon-bullhorn"></span>
                {% else %}
                    <span class="glyphicon glyphicon-alert"></span>
                {% endif %}
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                &emsp;{{ message|safe }}
            </div>
        {% endfor %}
    </div>
    <div class=col-md-2></div>
</div>

premierlangage-master/server/serverpl/playexo/templates/playexo/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        
        <!-- Header info -->
        {% block head %}{% endblock %}
        
        <!-- Title -->
        <title>{% block title %}UPEM - PL 2017/2018{% endblock %}</title>
        
        <!-- Load the tag library -->
        {% load static %}
        {% block tag %}{% endblock %}
        
        <!-- favicon -->
        <link rel="shortcut icon" href="{% static 'playexo/favicon.ico' %}" />       
        
        {% block css %}{% endblock %}
        <script src="{% static 'js/jquery_3.1.1.js' %}" ></script>
        <link rel="stylesheet" href="{% static '/css/bootstrap_4.css' %}" />
        <script src="{% static 'js/bootstrap_4.js' %}" ></script>
        
        <link rel="stylesheet" href="{% static '/css/bootstrap_3.3.7.css' %}" />
        <script src="{% static 'js/bootstrap_3.3.7.js' %}" ></script>
        <link rel="stylesheet" href="{% static 'playexo/css/exo_info.css' %}" />
        <link rel="stylesheet" href="{% static 'playexo/css/pywims_exos.css' %}">
        <link rel="stylesheet" href="{% static 'playexo/css/footer.css' %}">
        <link rel="stylesheet" href="{% static 'css/classmanagement.css' %}" />
        <link rel="stylesheet" href="{% static 'css/block_chart.css' %}" />
        {% block header_script %}{% endblock %}
    
    </head>
    
    <body>
        <div id="header">
            {% block topbar %}{% include "playexo/top_bar.html" %}{% endblock %}
        </div>
        <div id="content">
            {% block alert %}{% include "playexo/alert.html" %}{% endblock %}
            
            {% block content %}
                <!-- State -->
                {% block state %}
                {% endblock %}
                

                <div class="row">
                    <div class="col-md-1"></div>
                    <div class="col-md-2">
                        <!-- Navigation -->
                        {% block navigation %}
                        {% endblock %}
                    </div>
                    <div class="col-md-8">
                        <!-- Exo -->
                        {% block exo %}
                        {% endblock %}
                    </div>
                    <div class="col-md-1"></div>
                </div>
            {% endblock %}
            
            {% block end_script %}{% endblock %}
            <script src="{% static 'playexo/js/footer.js' %}"></script> 
        </div>
        <div id="footer">
            <footer class="footer">
                {% block footer %}{% include "playexo/footer.html" %}{% endblock %}
            </footer>
        </div>
    </body>
</html>

premierlangage-master/server/serverpl/playexo/templates/playexo/default_nav.html
{% extends "playexo/default_state.html" %}

{% load static %}

{% block navigation %}
    <div id="navigation" class="btn-group-vertical" style="width: 100%; margin-bottom: 15px;">
        <!-- PLTP -->
        {% if pl_sha1 %}
            <a style="white-space: normal;" href="{{ request.path }}?action=pltp" type="button" class="btn btn-default  btn-lg">{{ pltp_title }}</a>
        {% else %}
            <a style="white-space: normal;" href="{{ request.path }}?action=pltp" type="button" class="btn btn-default  btn-lg active">{{ pltp_title }}</a>
        {% endif %}
        <!-- Every PL -->
        {% for item  in pl_list %} 
            {% if pl_sha1 == item.0.sha1 %}
                <a style="white-space: normal;" href="{{ request.path }}?action=pl&pl_sha1={{item.0.sha1}}" type="button" class="btn btn-default btn-type{{ item.1 }} btn-lg active">
                    {{ item.2 }}
                </a>
            {% else %}
                <a style="white-space: normal;" href="{{ request.path }}?action=pl&pl_sha1={{item.0.sha1}}" type="button" class="btn btn-default btn-type{{ item.1 }} btn-lg">
                    {{ item.2 }}
                </a>
            {% endif %}
        {% endfor %}
    </div>
    <br>
{% endblock %}

premierlangage-master/server/serverpl/playexo/templates/playexo/default_pl_exo.html
{% extends custom_nav %}


{% block tag %}
    {% load markdown_deux_tags %}
    {% load bootstrap3 %}
    {% load static %}
{% endblock %}

{% block header_script %}
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [['\\(','\\)'],],
            skipTags: ["script","noscript","style"],
        }
    });
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML"></script>
{% endblock %}


{% block exo %}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="text-center"><h1>{% if 'title'%}{{ title }}{% endif %}</h1></div>
            <div class="text-left">{% if 'author' %}{{ author }}{% endif %}</div>
        </div>
        
        <div class="panel-body">
            {% if 'text'%}{{ text|markdown }}{% endif %}
            {% if 'texth'%}{{ texth|safe }}{% endif %}
            
            {% block feedback %}
                <div id="feedback_success" class="alert alert-success feedback" style="display: None"></div>
                <div id="feedback_info" class="alert alert-info feedback" style="display: None"></div>
                <div id="feedback_danger" class="alert alert-danger feedback" style="display: None"></div>
            {% endblock %}
            <br>
            
            {% csrf_token %}
            <div id="form">
                {% block form %}{% endblock %}
            </div>
            
            <br>
            <center>
                <div id="default_button" class="btn-group">
                        <a type=button class="btn btn-warning" href="/playexo/activity/?action=reset"><span class="glyphicon glyphicon-refresh"></span> Réinitialiser</a>
                        <button id="save_button" class="btn btn-default btn-info"><span class="glyphicon glyphicon-floppy-disk"></span> Sauvegarder</button>
                        <button id="submit_button" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Valider</button>
                </div>
                <div id="next_button" style="display: None; color: white;">
                    <a type="button" class="btn btn-lg btn-success" href="/playexo/activity/?action=next">
                        Suivant&emsp;<span class="glyphicon glyphicon-arrow-right"></span>
                    </a>
                </div>
            </center>
            <br>
        </div>
    </div>
{% endblock %}

{% block end_script %}
<!--  script executed after page is loaded -->
<script>
$( document ).ready(function(){
    if(window.top != window.self) {
        $('#home-link').remove();
    }

    $( "#submit_button" ).click(function() {
        var inputs = getInputs();

        var status = {requested_action: 'submit', inputs: inputs};
        $.ajax({
            type : "POST",
            url : "/playexo/activity/",
            data: JSON.stringify(status, null, '\t'),
            contentType: 'application/json;charset=UTF-8',
            success: function(returned_status) {
                status = returned_status;
                onReturn(status.feedback_type, status.feedback);
            }
        });
    });
    
    $( "#save_button" ).click(function() {
        var inputs = getInputs();

        var status = {requested_action: 'save', inputs: inputs};
        $.ajax({
            type : "POST",
            url : "/playexo/activity/",
            data: JSON.stringify(status, null, '\t'),
            contentType: 'application/json;charset=UTF-8',
            success: function(returned_status) {
                status = returned_status;
                onReturn(status.feedback_type, status.feedback);
            }
        });
    });
});

</script>

<script>
function wait(ms){
    var start = new Date().getTime();
    var end = start;
    while(end < start + ms) {
        end = new Date().getTime();
    }
}

function getInputs(){
    var inputs = {};
    $( "[id^='form_']" ).each(function() {
        var type = this.id.slice(5,8); // type of field, a 3 letter code, cf input tag defs
        var id = this.id.slice(9); // name of the variable
        var value = $(this).val();
        if ($(this).is(':radio')) {
            if($(this).is(':checked')) {
                inputs[id]=value;
            }
        }
        else if ($(this).is(':checkbox')) {
            if($(this).is(':checked')) {
                if (id in inputs) {
                    inputs[id].push(value);
                }
                else {
                    inputs[id] = [value]
                }
            }
        }
        else {
            inputs[id]=value;
        }
    });
    return inputs;
}

function onReturn(feedback_type, feedback) {
    $( "#feedback_success" ).hide();
    $( "#feedback_success").css('animation', 'fadeOut 1s forwards');
    $( "#feedback_info" ).hide();
    $( "#feedback_info").css('animation', 'fadeOut 1s forwards');
    $( "#feedback_danger" ).hide();
    $( "#feedback_danger").css('animation', 'fadeOut 1s forwards');
    
    $('#navigation').load(document.URL + " #navigation>*","");
    if (feedback_type == "success") {
        $( "#default_button" ).toggle();
        $( "#next_button" ).toggle();
        $( "#feedback_success" ).html(feedback);
        MathJax.Hub.Queue(["Typeset",MathJax.Hub,feedback_success]);
        $( "#feedback_success" ).toggle();
        $( "#feedback_success").css('animation', 'growIn 1s forwards');
    }
    else if (feedback_type == "info") {
        $( "#feedback_info" ).html(feedback);
        MathJax.Hub.Queue(["Typeset",MathJax.Hub,feedback_info]);
        $( "#feedback_info" ).toggle();
        $( "#feedback_info").css('animation', 'growIn 1s forwards');
    }
    else {
        $( "#feedback_danger" ).html(feedback);
        MathJax.Hub.Queue(["Typeset",MathJax.Hub,feedback_danger]);
        $( "#feedback_danger" ).toggle();
        $( "#feedback_danger").css('animation', 'growIn 1s forwards');
    }
}
</script>
{% endblock %}

premierlangage-master/server/serverpl/playexo/templates/playexo/top_bar.html
{% load static %}

<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" style="height: 50px">
        <span class="navbar-toggler-icon" style="height; 40px"></span>
    </button>
    
    <div class="navbar-left" style="width: 350px">
        <img alt="UPEM" src="{% static 'img/upem.png' %}" height="44" width="88" /> 
        <a class="navbar-brand" href="/">Premier Langage</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar">        
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="/">Mes Cours</a>
            </li>
            {% if request.user.pluser.can_load %}
                <li class="nav-item">
                    <a class="nav-link" href="/gitload/">Gitload</a>
                </li>
            {% endif %}
            {% if request.user.pluser.can_load %}
                <li class="nav-item">
                    <a class="nav-link" href="/documentation/">Documentation</a>
                </li>
            {% endif %}
            {% if request.user.pluser.is_admin or request.user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="/admin/">Administration</a>
                </li>
            {% endif %}
        </ul>
        
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <span class="glyphicon glyphicon-user"></span>
                    {% firstof request.user.get_full_name request.user.get_username "Non Connecté" %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item"><span class="glyphicon glyphicon-envelope"></span>&emsp;{% firstof user.email "N/A" %}</a>
                    <a class="dropdown-item" href="/courses/cycle_color_blindness/?from={{ request.path|urlencode }}" ><span class="glyphicon glyphicon-eye-close"></span>&emsp;Daltonisme: {{ request.user.pluser.get_color_blindness_display }}</a>
                </div>
            </li>
            <li class="nav-item">
                <a href="/playexo/not_authenticated/"><span class="glyphicon glyphicon-off"></span></a>
            </li>
        </ul>
    </div>
</nav>